### ISSUE TITLE
ENH: Support native osx-arm64 conda install

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/conda-base#77]
### Context
Now that bioconda supports osx-arm64, we can finally try to make a native environment, which will speed up local builds by around a factor of 2.

There's quite a lot of work to do: all our dependencies will need to be supported by osx-arm64, but it should be doable!

This issue is a tracker, to help us see what's still missing.

### Tasks

- [ ] Migrate all bioconda dependencies to osx-arm64:

    - [x] snakemake-minimal
    - [x] pathogen-embed
    - [x] nextstrain-cli
    - [x] snakemake
    - [x] bx-python: https://github.com/bioconda/bioconda-recipes/pull/49092
    - [x] treetime 
    - [x] evofr
    - [x] bcbio-gff
    - [x] pango_aliasor
    - [x] epiweeks
    - [x] pyfastx: https://github.com/bioconda/bioconda-recipes/pull/49093
    - [x] nextclade: https://github.com/bioconda/bioconda-recipes/pull/49095
    - [x] nextclade2: https://github.com/bioconda/bioconda-recipes/pull/49097
    - [x] iqtree: https://github.com/bioconda/bioconda-recipes/pull/49090
    - [x] fasttree: https://github.com/bioconda/bioconda-recipes/pull/49100
    - [x] auspice: https://github.com/bioconda/bioconda-recipes/pull/49103
    - [x] csvtk: https://github.com/bioconda/bioconda-recipes/pull/49094
    - [x] nextalign: https://github.com/bioconda/bioconda-recipes/pull/49096
    - [x] seqkit: https://github.com/bioconda/bioconda-recipes/pull/49099
    - [x] mafft: https://github.com/conda-forge/mafft-feedstock/issues/3
    - [x] raxml: https://github.com/bioconda/bioconda-recipes/pull/49098
    - [x] vcftools: https://github.com/bioconda/bioconda-recipes/pull/49102
    - [x] augur: blocked on xopen, blocked on python-isal, blocked on isa-l, unless we make python-isal optional for xopen which should be doable
    - [x] xopen: fighting here https://github.com/conda-forge/xopen-feedstock/pull/45
    - [ ] gzip: https://github.com/conda-forge/gzip-feedstock/pull/9

- [ ] Ensure conda-forge packages are available under osx-arm64
- [ ] https://github.com/nextstrain/conda-base/pull/80

**Comment by jameshadfield** [comment]
Are we still missing [tsv-utils which is osx-64/linux-64](https://anaconda.org/bioconda/tsv-utils)?

https://github.com/nextstrain/conda-base/blob/224ad3997cc7ca17fa6fa2ed29ade37c21b3fece/src/recipe.yaml#L83

**Comment by corneliusroemer** [comment]
@jameshadfield no 😀 I migrated it to conda-forge a few days ago as it's of general utility and not bio limited. check it out at conda-forge/tsv-utils

**Comment by victorlin** [comment]
There are two steps here - the first one is making sure that dependencies can be installed natively which looked like a big undertaking, thank you for taking care of that!

Next, we have to update the build to produce the package for `osx-arm64`. I think this is what needs to be done:

1. Use `osx-arm64` here: https://github.com/nextstrain/conda-base/blob/e5090a8092d7f06eeb1392ae223cdedf849ab0ac/devel/conda-subdir#L17-L18
2. Use `macos-14` here: https://github.com/nextstrain/conda-base/blob/e5090a8092d7f06eeb1392ae223cdedf849ab0ac/.github/workflows/ci.yaml#L29-L36

For (2) I think we'll want to append to the list rather than replace `macos-12` so that there will still be a native package for Intel Macs.

**Comment by corneliusroemer** [comment]
Nice @victorlin - I didn't see this comment of yours just now but came to the same conclusions when trying a PR. I've made one here:
- #80 

It turns out that gzip isn't yet available for osx-arm64. We could potentially drop that for osx-arm64 as gzip is available from the system on macOS arm64.

But I made a migration pr to conda-forge anyways:
- https://github.com/conda-forge/gzip-feedstock/pull/9

**Comment by victorlin** [comment]
@corneliusroemer let me know if you need any help pushing #80 through. I've prioritized task under my name at our biweekly priorities meetings because it seems close to done, and I think it'd be great to take advantage of all the work that you and others have done to make it possible.
